
# application name
spring.application.name=moneymanager

# MY SQL Config
spring.datasource.url=${MY_SQL_URL}
spring.datasource.username=${MY_SQL_USER}
spring.datasource.password=${MY_SQL_PASSWORD}


server.servlet.context-path=${SERVLET_PATH}

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# brevo Email Sending config
spring.mail.host=${BREVO_HOST}
spring.mail.port=${BREVO_PORT}
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${BREVO_MAIL_FROM}

## front end url
money.manager.frontend.url=${FRONTEND_URL}
app.activation.url=${MONEY_MANAGER_BACKEND_URL}
## jwt secret
jwt.secret=${JWT_SECRET}

spring.profiles.active=prod